### ISSUE TITLE
Use correct name when dependency has been renamed

### ISSUE THREAD

**Issue by jonhoo** [kbknapp/cargo-outdated#133]
Cargo [recently](https://github.com/rust-lang/cargo/blob/0dd53841d30816ec0d79d879de71d7adc360bdc5/src/doc/src/reference/unstable.md#rename-dependency) got support for renaming dependencies. That is, you can do:
```toml
cargo-features = ["rename-dependency"]
# ...
[dependencies]
bar = { version = "0.1", package = "foo" }
```
To import the crate `foo` under the name `bar`. However, this seems to confuse `cargo-outdated`. Specifically, it looks for `bar` instead of `foo` in the registry, which generally won't exist.
