### ISSUE TITLE
Native library conflicts due to unexpected version bump

### ISSUE THREAD

**Issue by netvl** [kbknapp/cargo-outdated#184]
If you run the latest version of `cargo-outdated` against the following manifest:
```toml
[package]
name = "testresolv"
version = "0.1.0"
edition = "2018"

[dependencies]
rusqlite = "0.18.0"
refinery = { version = "0.1.10", features = ["rusqlite"] }
```

you will get the following error:
```
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `rusqlite v0.18.0`
    ... which is depended on by `refinery-migrations v0.1.0`
    ... which is depended on by `refinery v0.1.10`
    ... which is depended on by `testresolv v0.1.0 (/tmp/cargo-outdatedIHYCuQ)`
versions that meet the requirements `^0.14` are: 0.14.0

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.17.0`
    ... which is depended on by `rusqlite v0.21.0`
    ... which is depended on by `testresolv v0.1.0 (/tmp/cargo-outdatedIHYCuQ)`

failed to select a version for `libsqlite3-sys` which could resolve this conflict
```

This is kinda unexpected, because the manifest explicitly specifies that `rusqlite` version is `0.18.0`, not `0.21.0`.

The project itself builds just fine without any issues with this setup of dependencies.
