### ISSUE TITLE
unknown cargo feature `named-profiles` (nightly)

### ISSUE THREAD

**Issue by mverleg** [kbknapp/cargo-outdated#186]
I'm using named-profiles in my Cargo.toml to support my ``[profile.test_coverage]``.

When I run either of these,

    cargo outdated --exit-code 1
    cargo -Z unstable-options -Z config-profile outdated --exit-code 1

I get

    error: failed to parse manifest at `/path/to/project/Cargo.toml`
    
    Caused by:
      unknown cargo feature `named-profiles`

I'm using

    Rust: nightly-2019-12-20-x86_64-unknown-linux-gnu
    cargo-outdated: v0.9.2

``cargo build`` does work, so I guess it uses a different Cargo version or something?

**Comment by mverleg** [comment]
(In case cargo-outdated doesn't support nightly, I guess this issue is just a warning about possible upcoming change. I forgot that this functionality depends on nightly.)

**Comment by deg4uss3r** [comment]
This appears to have been resolved with the bumps to the `cargo` dependency. Can you confirm @mverleg? 

For example this manifest works: 
```toml
cargo-features = ['named-profiles']
[package]
name = "foo"
version = "0.1.0"
authors = ["Degausser"]
edition = "2018"

[profile.test_coverage]
inherits = "dev"
opt-level = 1
overflow-checks = false

[dependencies]
rand = "0.7"
```
