### ISSUE TITLE
warning: Feature uuidv07 of package diesel has been obsolete in version 1.4.4

### ISSUE THREAD

**Issue by frederikhors** [kbknapp/cargo-outdated#216]
I have this in my **Cargo.toml**:

```toml
[dependencies]
actix-web = "=2.0.0"
actix-rt = "=1.0.0"
chrono = { version = "=0.4.11", features = ["serde"] }
diesel = { version = "=1.4.4", features = ["postgres", "r2d2", "uuidv07", "chrono"] }
diesel_migrations = "=1.4.0"
dotenv = "=0.15.0"
env_logger = "=0.7.1"
lazy_static = "=1.4.0"
log = "=0.4.8"
r2d2 = "=0.8.8"
serde = "=1.0.105"
serde_json = "=1.0.50"
uuid = { version = "=0.8.1", features = ["serde", "v4"] }
```

It works because of `uuidv07` feature but `cargo outdated` gives me this warning:

`warning: Feature uuidv07 of package diesel has been obsolete in version 1.4.4`.

**Why?**
