### ISSUE TITLE
strip in Cargo.toml gets no love from cargo outdated

### ISSUE THREAD

**Issue by virtualritz** [kbknapp/cargo-outdated#231]
In my `Cargo.toml` I have:
```toml
[profile.release]
strip = "symbols"
```

This makes `cargo outdated` (v0.9.11) fall over:
```
❯ cargo outdated
error: failed to parse manifest at `Cargo.toml`

Caused by:
  unknown cargo feature `strip`
```

Strip is a [supported feature in nightly since a while](https://github.com/rust-lang/cargo/issues/3483#issuecomment-631395566).

**Comment by deg4uss3r** [comment]
Can you provide a full breaking `Cargo.toml`? As the `Cargo.toml` below works fine for me on MacOS 10.15.5:

```toml
cargo-features = ["strip"]

[package]
name = "stripit"
version = "0.1.0"
authors = ["degausser"]
edition = "2018"

[dependencies]
rand = "0.1"

[profile.release]
strip = "symbols"
```

produces: 

```
❯ cargo outdated -v
  Parsing... current workspace
Resolving... current workspace
  Parsing... compat workspace
 Updating... compat workspace
    Updating crates.io index
Resolving... compat workspace
  Parsing... latest workspace
 Updating... latest workspace
    Updating crates.io index
      Adding cfg-if v0.1.10
      Adding getrandom v0.1.14
    Updating libc v0.1.12 -> v0.2.73
    Removing log v0.2.5
      Adding ppv-lite86 v0.2.8
    Updating rand v0.1.4 -> v0.7.3
      Adding rand_chacha v0.2.2
      Adding rand_core v0.5.1
      Adding rand_hc v0.2.0
      Adding wasi v0.9.0+wasi-snapshot-preview1
Resolving... latest workspace
Resolving... package status
 Printing... list format
Name        Project  Compat  Latest   Kind    Platform
----        -------  ------  ------   ----    --------
rand        0.1.4    ---     0.7.3    Normal  ---
rand->libc  0.1.12   ---     0.2.73   Normal  ---
rand->log   0.2.5    ---     Removed  Normal  ---
```

```
❯ cargo outdated --version
cargo-outdated v0.9.11
```
