### ISSUE TITLE
Failure with Patched Workspace Path Dependencies

### ISSUE THREAD

**Issue by theduke** [kbknapp/cargo-outdated#275]
I've come across a situation where `cargo outdated` fails with the error `failed to resolve patches for https://github.com/rust-lang/crates.io-index`.

This happens when:

* a dependency that is not published on crates.io is specified with a regular version 
* A (workspace) `[patch]` override specifies a local path for said dependency

Eg: 

`root/crate1/Cargo.toml`:
```toml
[dependencies]
somedep = "0.1"
```

`root/Cargo.toml`:
```toml
[workspace]
members = ["crate1"]

[patch.crates-io]
somedep = { path = "../somedep" }
```
