### ISSUE TITLE
Not showing latest version

### ISSUE THREAD

**Issue by krishnaTORQUE** [kbknapp/cargo-outdated#362]
Not showing latest version

Cargo.toml
```toml
[dependencies]
tokio = { version = "^1.28.2", features = ["full"] }
```

Its been 22 days since `tokio@1.29.1`  released but its not showing even right now.
