### ISSUE TITLE
Filter out versions not compatible with current Rust version

### ISSUE THREAD

**Issue by tyilo** [kbknapp/cargo-outdated#412]
Similar to what adding the following to `.cargo/config.toml` does:
```toml
[resolver]
incompatible-rust-versions = "fallback"
```

This could either be done with a new flag or by reading the users `.cargo/config.toml`.
