### ISSUE TITLE
cargo outdated errors if a package removed a feature in a newer version

### ISSUE THREAD

**Issue by euclio** [kbknapp/cargo-outdated#84]
To reproduce:

Cargo.toml:

```toml
[package]
name = "dep-test"
version = "0.1.0"

[dependencies]
handlebars = { version = "0.25", features = ["serde_type"] }
```

```sh
$ cargo outdated -R
error: Package `handlebars v0.29.1` does not have these features: `serde_type`
```
